/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MembershipPlan {
  'id' : bigint,
  'featured' : boolean,
  'features' : Array<string>,
  'period' : string,
  'name' : string,
  'price' : string,
}
export interface Trainer {
  'id' : bigint,
  'bio' : string,
  'title' : string,
  'cert' : string,
  'name' : string,
  'experience' : string,
  'imageUrl' : string,
}
export interface Transformation {
  'id' : bigint,
  'result' : string,
  'duration' : string,
  'name' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMembershipPlan' : ActorMethod<
    [string, string, string, boolean, Array<string>],
    bigint
  >,
  'createTrainer' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'createTransformation' : ActorMethod<[string, string, string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMembershipPlanById' : ActorMethod<[bigint], [] | [MembershipPlan]>,
  'getMembershipPlans' : ActorMethod<[], Array<MembershipPlan>>,
  'getTrainerById' : ActorMethod<[bigint], [] | [Trainer]>,
  'getTrainers' : ActorMethod<[], Array<Trainer>>,
  'getTransformationById' : ActorMethod<[bigint], [] | [Transformation]>,
  'getTransformations' : ActorMethod<[], Array<Transformation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeDefaultData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];