/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MembershipPlan = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'features' : IDL.Vec(IDL.Text),
  'period' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Text,
});
export const Trainer = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'cert' : IDL.Text,
  'name' : IDL.Text,
  'experience' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Transformation = IDL.Record({
  'id' : IDL.Nat,
  'result' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMembershipPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createTrainer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTransformation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembershipPlanById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MembershipPlan)],
      ['query'],
    ),
  'getMembershipPlans' : IDL.Func([], [IDL.Vec(MembershipPlan)], ['query']),
  'getTrainerById' : IDL.Func([IDL.Nat], [IDL.Opt(Trainer)], ['query']),
  'getTrainers' : IDL.Func([], [IDL.Vec(Trainer)], ['query']),
  'getTransformationById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Transformation)],
      ['query'],
    ),
  'getTransformations' : IDL.Func([], [IDL.Vec(Transformation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDefaultData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MembershipPlan = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'features' : IDL.Vec(IDL.Text),
    'period' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Text,
  });
  const Trainer = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'cert' : IDL.Text,
    'name' : IDL.Text,
    'experience' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Transformation = IDL.Record({
    'id' : IDL.Nat,
    'result' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMembershipPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createTrainer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTransformation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembershipPlanById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MembershipPlan)],
        ['query'],
      ),
    'getMembershipPlans' : IDL.Func([], [IDL.Vec(MembershipPlan)], ['query']),
    'getTrainerById' : IDL.Func([IDL.Nat], [IDL.Opt(Trainer)], ['query']),
    'getTrainers' : IDL.Func([], [IDL.Vec(Trainer)], ['query']),
    'getTransformationById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Transformation)],
        ['query'],
      ),
    'getTransformations' : IDL.Func([], [IDL.Vec(Transformation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDefaultData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };